# 请根据自身需求修改
debug: true
log_dir: ./log
# #
db_url: sqlite:///app_dev.sqlite
db_async_url: sqlite+aiosqlite:///app_dev.sqlite
redis_host:
redis_port:
redis_db:
redis_password:
snow_worker_id: 0
snow_datacenter_id: 0
