# 请根据自身需求修改
debug: false
log_dir: ./log
# #
snow_worker_id: 0
snow_datacenter_id: 0
redis_host:
redis_port:
redis_db:
redis_password:
db_url: sqlite:///app_prod.sqlite
db_async_url: sqlite+aiosqlite:///app_prod.sqlite
