# 请根据自身需求修改
appname: DbyApp-prod
appversion: 1.0.0
debug: false
log_dir: ./log
is_disable_docs: true
# #
redis_host:
redis_port:
redis_db:
redis_password:
redis_max_connections:
db_url: sqlite:///app_prod.sqlite
db_async_url: sqlite+aiosqlite:///app_prod.sqlite
